spring_boot_api:
    name: spring-boot-api
    namespace: spring
    stage: dev
    config_map:
        cm_config:
            config.json: |
                {
                  "animals": {
                    "cow": "moo",
                    "sheep": "beee",
                    "pig": "oink"
                  }
                }
    deployment:
      replicas: 3
      image: busybox
      image_tag: latest
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 0
          maxSurge: 1
      resources:
        requests:
          memory: "100Mi"
          cpu: "250m"
        limits:
          memory: "200Mi"
          cpu: "500m"
      terminationGracePeriodSeconds: 30
