apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: spring-boot-api-applicationset
  namespace: {{ .Values.namespace }}
spec:
  generators:
    - list:
        elements:
          {{- toYaml .Values.app_set_elements | nindent 10 }}
  template:
    metadata:
      name: {{ printf  "'{{name}}'" }}
    spec:
      project: {{ .Values.project_name }}
      source:
        {{- toYaml .Values.repo | nindent 8 }}
      destination:
        server: {{ printf  "'{{cluster}}'" }}
        namespace: {{ printf "'{{namespace}}'" }}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
