apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: spring-boot-api-applicationset
  namespace: {{ .Values.namespace }}
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            app: {{ .Values.repo.helm.releaseName }}
  template:
    metadata:
      name: {{ .Values.repo.helm.releaseName }}-{{`{{metadata.labels.stage}}`}}
    spec:
      project: {{ .Values.project_name }}
      source:
        repoURL: {{ .Values.repo.repoURL }}
        targetRevision: {{ .Values.repo.targetRevision }}
        path: {{ .Values.repo.path }}
        helm:
          releaseName: {{ .Values.repo.helm.releaseName }}
          parameters:
            - name: stage
              value: '{{`{{metadata.labels.stage}}`}}'
          valueFiles:
            {{- toYaml .Values.repo.helm.valueFiles | nindent 12 }}
      destination:
        server: '{{`{{server}}`}}'
        namespace: spring
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
