apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: spring-boot-api-applicationset
  namespace: {{ .Values.namespace }}
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            app: {{ .Values.repo.helm.releaseName }}
  template:
    metadata:
      name: {{ .Values.repo.helm.releaseName }}-{{`{{metadata.labels.stage}}`}}
    spec:
      project: {{ .Values.project_name }}
      source:
        {{- toYaml .Values.repo | nindent 8 }}
      destination:
        server: '{{`{{server}}`}}'
        namespace: spring
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
