apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.spring_boot_api.name }}
  namespace: {{ .Values.spring_boot_api.namespace }}
  labels:
    app: {{ .Values.spring_boot_api.name }}
    stage: {{ .Values.stage }}
spec:
  replicas: {{- if eq .Values.stage "prod" }} 5
    {{- else if eq .Values.stage "dev" }} 3
    {{- else }} 1
    {{- end }}
  {{- with .Values.spring_boot_api.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Values.spring_boot_api.name }}
  template:
    metadata:
      annotations:
        checksum/cm: {{ include (print $.Template.BasePath "/config.map.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      labels:
        app: {{ .Values.spring_boot_api.name }}
        stage: {{ .Values.stage }}
    spec:
      {{- with .Values.spring_boot_api.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.spring_boot_api.terminationGracePeriodSeconds }}
      containers:
        - name: {{ .Values.spring_boot_api.container.name }}
          image: {{ .Values.spring_boot_api.container.image }}
          imagePullPolicy: {{ .Values.spring_boot_api.container.imagePullPolicy }}
          {{- with .Values.spring_boot_api.container.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            {{- range .Values.spring_boot_api.container.ports }}
            - containerPort: {{ .containerPort }}
              protocol: {{ .protocol | default "TCP" }}
            {{- end }}
          {{- with .Values.spring_boot_api.container.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.spring_boot_api.container.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          args:
            - "--spring.profiles.active={{ .Values.stage }}"
          {{- with .Values.spring_boot_api.container.lifecycle }}
          lifecycle:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          livenessProbe:
            {{- toYaml .Values.spring_boot_api.container.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.spring_boot_api.container.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.spring_boot_api.container.resources | nindent 12 }}
