apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{  .Values.spring_boot_api.name }}
  namespace: {{  .Values.spring_boot_api.namespace }}
spec:
  replicas: {{ .Values.spring_boot_api.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: {{  .Values.spring_boot_api.name }}
  template:
    metadata:
      labels:
        app: {{  .Values.spring_boot_api.name }}
    spec:
      containers:
        - name: main
          image: busybox:stable
          ports:
            - containerPort: 8080
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          args:
            - "--spring.profiles.active={{ .Values.spring_boot_api.stage }}"
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              memory: "100Mi"
              cpu: "250m"
            limits:
              memory: "200Mi"
              cpu: "500m"
      terminationGracePeriodSeconds: 30
      lifecycle:
        preStop:
          exec:
            command: ["wget", "http://localhost:8080/service/shutdown"]
