apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.spring_boot_api.name }}-secret
  namespace: {{ .Values.spring_boot_api.namespace }}
type: Opaque
data:
  {{- range $key, $value := .Values.spring_boot_api.secret.data }}
  {{ $key }}: {{ randAlphaNum 32 | b64enc }}
  {{- end }}
