apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: example-list-applicationset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: https://kubernetes.default.svc
            name: "Spring-Boot API dev"
            namespace: spring
          - cluster: https://kubernetes.default.svc
            name: "Spring-Boot API prod"
            namespace: spring
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/your-org/your-repo.git
        targetRevision: HEAD
        path: apps/{{name}}
      destination:
        server: '{{cluster}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
